version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "10008:8080"
      - "10005:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    command:
      - sh
      - -c
      - |
        curl https://get.docker.com/ > dockerinstall
        chmod 777 dockerinstall
        sh dockerinstall
        apt-get update
        apt-get install -y docker-compose
        /usr/local/bin/jenkins.sh
