version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "10008:8080"
      - "10005:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_home/:/var/jenkins_home
    user: root
    command:
      - sh
      - -c
      - |
        curl https://get.docker.com/ > dockerinstall
        chmod 777 dockerinstall
        sh dockerinstall
        apt-get update
        apt-get install -y docker-compose
        /usr/local/bin/jenkins.sh
    healthcheck:
      test: sh -c "sleep 30 && curl --fail http://localhost:8080 || exit 1"
      interval: 1s
      retries: 120
      timeout: 5s
  jenkins-cli-runner:
    image: openjdk:11-jdk
    container_name: jenkins-cli-runner
    links:
      - jenkins:jenkins
    command:
      - sh
      - -c
      - |
        while true; do wget http://jenkins:8080/jnlpJars/jenkins-cli.jar && break || sleep 1s; done
        java -jar jenkins-cli.jar -s http://jenkins:8080/ -auth admin:$(cat /secrets/initialAdminPassword) install-plugin ant build-timeout email-ext github-branch-source gradle javax-mail-api ldap matrix-auth pam-auth workflow-aggregator pipeline-github-lib pipeline-stage-view ssh-slaves sshd timestamper ws-cleanup
    volumes:
      - ./jenkins_home/secrets:/secrets
